on: [push]

name: Expire container tags

jobs:
  expire-tags:
    runs-on: ubuntu-latest
    name: "expire-tags"
    steps:
      - uses: eumel8/expire-action@debug
        with:
          token: ${{secrets.TAGEXPIRE}}
          image_name: busybox%2Fbusybox
          days_treshold: 0
          protected_tags_regex: "2.*"
