on: [push]

name: Expire container tags

jobs:
  expire-tags:
    runs-on: ubuntu-latest
    name: "expire-tags"
    steps:
      - uses: eumel8/expire-action@1.0.2
        with:
          token: ${{secrets.TAGEXPIRE}}
          #repo_type: org
          #orgname: caas-team
          image_name: navlinkswebhook%2Fnavlinkswebhook
          days_treshold: 365
          protected_tags_regex: 2.*,1.*
